### ISSUE TITLE
Crashing on Boot

### ISSUE THREAD

**Issue by benyanke** [bigbrozer/docker-x2go-kde#3]
This seems quite useful - I'm getting the following error, which halts the startup.

```
Application: KCMInit (kdeinit5), signal: Segmentation fault
```

**Comment by bigbrozer** [comment]
Thanks for reporting this. As #1 has been fixed upstream, I did a refresh of base image **bigbrozer/x2go-base** to upgrade it from **ubuntu:xenial** to **ubuntu:17.04**.
